In [12]:
install.packages("languageserver")
install.packages('vtable')
install.packages('readr')
install.packages('dplyr')
install.packages('tidyverse')

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [13]:
library(readr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(vtable)

In [21]:
elec_data <- read.csv('anes_timeseries_cdf_csv_20220916.csv')
#having trouble uploading it to github rn

subset <- elec_data[, c("VCF0004", "VCF0114", "VCF0110", "VCF0104", "VCF0105a", "VCF0102","VCF0705","VCF0901a")]
subset <- na.omit(subset)
colnames(subset)[1]<-'year_of_study' #was VCF0004
colnames(subset)[2]<-'income_group' #was VCF0114
colnames(subset)[3]<-'education_4_cat' #was VCF0110
colnames(subset)[4]<-'gender' #was VCF0104
colnames(subset)[5]<-'race_ethnicity_seven' #was VCF0105a
colnames(subset)[6]<-'age_group' #was VCF0102
colnames(subset)[7]<-'vote_pres' #was VCF0705
colnames(subset)[8] <- "state_code" #was VCF0901a, state codes can be found on page 101 of appendices

subset

      year_of_study income_group education_4_cat gender race_ethnicity_seven
663   1952          4            2               2      1
664   1952          4            1               2      1
665   1952          3            2               2      1
666   1952          3            2               1      1
667   1952          1            2               2      1
668   1952          4            2               2      1
669   1952          1            1               2      1
670   1952          2            2               1      2
671   1952          1            2               2      1
672   1952          4            1               2      1
673   1952          3            2               2      1
674   1952          4            4               2      1
675   1952          4            2               2      1
676   1952          1            1               2      1
677   1952          1            2               2      1
678   1952          3            2               2      1
679   1952          4            1               2      1
680   1952          1            1               2      1
681   1952          2            2               1      1
682   1952          3            2               2      1
683   1952          4            2               2      1
684   1952          3            2               2      1
685   1952          4            1               2      1
686   1952          2            1               1      1
687   1952          0            2               2      1
688   1952          2            2               2      1
689   1952          1            2               2      1
690   1952          1            1               1      1
691   1952          3            2               2      1
692   1952          1            1               2      2
⋮     ⋮             ⋮            ⋮               ⋮      ⋮
68195 2020          1            4               1      2
68196 2020          3            4               1      1
68197 2020          4            3               1      1
68198 2020          2            3               2      2
68199 2020          1            2               1      1
68200 2020          4            3               2      1
68201 2020          3            4               2      1
68202 2020          1            3               2      2
68203 2020          1            2               2      1
68204 2020          5            4               2      1
68205 2020          4            3               1      4
68206 2020          1            3               1      9
68207 2020          4            4               1      3
68208 2020          1            1               2      5
68209 2020          2            4               2      1
68210 2020          2            1               2      1
68211 2020          1            2               2      2
68212 2020          3            4               2      1
68213 2020          4            3               2      1
68214 2020          3            1               1      1
68215 2020          1            1               1      2
68216 2020          1            3               2      1
68217 2020          4            3               1      1
68218 2020          1            2               2      1
68219 2020          0            4               2      1
68220 2020          2            3               2      1
68221 2020          4            4               2      1
68222 2020          3            2               1      5
68223 2020          3            3               2      1
68224 2020          3            4               2      3
      age_group vote_pres state_code
663   2         2         36
664   2         1         36
665   2         2         36
666   5         2         36
667   6         2         39
668   4         2         39
669   6         2         16
670   2         1         26
671   2         0         13
672   3         2         39
673   2         2         39
674   4         2         39
675   5         1         39
676   4         2         31
677   5         1         36
678   3         1         26
679   6         1         25
680   5         1         31
681   2         2         36
682   2         1         31
683   5         0         25
684   1         2         31
685   6         2         36
686   4         1         31
687   3         0         31
688   2         0         31
689   4         2         31
690   6         0         21
691   3         1         16
692   3         0         21
⋮     ⋮         ⋮         ⋮
68195 0         0         22
68196 3         0          6
68197 4         2         51
68198 2         0         26
68199 6         0         47
68200 6         1         51
68201 4         1         34
68202 5         1         37
68203 7         1         12
68204 1         1         25
68205 3         1         25
68206 2         1          6
68207 4         1          4
68208 2         0          8
68209 7         1         51
68210 2         0         29
68211 4         0         13
68212 4         2         47
68213 6         2         36
68214 6         1         31
68215 0         2         36
68216 4         0         55
68217 4         1         31
68218 6         2         22
68219 4         2         19
68220 2         0         12
68221 4         2         16
68222 4         1          6
68223 6         2         51
68224 3         1         51

In [22]:
#converting ints into factors for categorical variables, state code into character for converting to state name
subset$income_group <- as.factor(subset$income_group)
subset$education_4_cat <- as.factor(subset$education_4_cat)
subset$gender <- as.factor(subset$gender)
subset$race_ethnicity_seven <- as.factor(subset$race_ethnicity_seven)
subset$age_group <- as.factor(subset$age_group)
subset$vote_pres <- as.factor(subset$vote_pres)
subset$state_code <- as.character(subset$state_code)

In [28]:
#filtering for after 1980, not including 1980
post_1980 <- filter(subset, year_of_study > 1980)

#if we want to filter out all missing, i have included the code to rename
#the missing levels as comments
post_180_nomissing <- filter(post_1980, 
                       income_group != 0, 
                       education_4_cat != 0, 
                       gender != 0,
                       race_ethnicity_seven != 9,
                       age_group != 0,
                       vote_pres != 0,
                            vote_pres != 3, #remove 3rd party 
                            state_code != 99,
                            state_code != 00)

In [24]:
state_fips <- data.frame(
  state_code = c(
    1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23,
    24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56
  ),
  state_name = c(
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut",
    "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois",
    "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
    "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota",
    "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming"
  )
)


post_180_nomissing$state_name <- state_fips$state_name[match(post_180_nomissing$state_code, state_fips$state_code)]

post_180_nomissing

      year_of_study income_group education_4_cat gender race_ethnicity_seven
1     1984          1            2               2      2
2     1984          5            3               1      1
3     1984          3            3               2      1
4     1984          3            2               2      1
5     1984          4            4               1      1
6     1984          5            4               2      1
7     1984          4            3               1      1
8     1984          3            4               1      1
9     1984          5            4               2      1
10    1984          4            3               2      1
11    1984          3            1               2      1
12    1984          3            3               1      1
13    1984          4            4               2      1
14    1984          1            1               2      1
15    1984          3            2               2      1
16    1984          3            4               2      1
17    1984          3            2               2      1
18    1984          4            3               1      1
19    1984          1            4               1      1
20    1984          5            4               1      1
21    1984          2            2               2      1
22    1984          4            4               2      1
23    1984          3            2               2      1
24    1984          4            2               1      1
25    1984          3            3               1      1
26    1984          3            3               2      1
27    1984          1            2               2      1
28    1984          5            4               2      1
29    1984          3            2               1      1
30    1984          4            4               2      1
⋮     ⋮             ⋮            ⋮               ⋮      ⋮
19712 2020          3            3               2      5
19713 2020          4            4               2      1
19714 2020          1            4               1      1
19715 2020          4            4               1      1
19716 2020          3            3               2      2
19717 2020          3            3               2      6
19718 2020          5            4               1      1
19719 2020          2            4               1      1
19720 2020          1            3               2      1
19721 2020          3            2               1      1
19722 2020          2            3               2      1
19723 2020          3            3               2      5
19724 2020          4            3               1      1
19725 2020          4            3               2      1
19726 2020          3            4               2      1
19727 2020          1            3               2      2
19728 2020          1            2               2      1
19729 2020          5            4               2      1
19730 2020          4            3               1      4
19731 2020          4            4               1      3
19732 2020          2            4               2      1
19733 2020          3            4               2      1
19734 2020          4            3               2      1
19735 2020          3            1               1      1
19736 2020          4            3               1      1
19737 2020          1            2               2      1
19738 2020          4            4               2      1
19739 2020          3            2               1      5
19740 2020          3            3               2      1
19741 2020          3            4               2      3
      age_group vote_pres state_code state_name
1     6         1         37         North Carolina
2     6         2         39         Ohio
3     2         2         26         Michigan
4     4         1         47         Tennessee
5     3         2         26         Michigan
6     4         2         26         Michigan
7     3         2         26         Michigan
8     2         2         12         Florida
9     2         2         12         Florida
10    6         2         12         Florida
11    6         1         26         Michigan
12    2         2         47         Tennessee
13    7         1         34         New Jersey
14    7         1         41         Oregon
15    6         2         36         New York
16    3         2         36         New York
17    5         1         9          Connecticut
18    3         2         9          Connecticut
19    1         1         36         New York
20    3         2         36         New York
21    2         1         26         Michigan
22    2         1         47         Tennessee
23    5         2         36         New York
24    5         2         12         Florida
25    1         2         13         Georgia
26    1         2         13         Georgia
27    7         1         42         Pennsylvania
28    4         1         26         Michigan
29    3         2         39         Ohio
30    3         2         13         Georgia
⋮     ⋮         ⋮         ⋮          ⋮
19712 4         2         17         Illinois
19713 6         1         37         North Carolina
19714 7         1         48         Texas
19715 6         2         47         Tennessee
19716 3         1         48         Texas
19717 2         2         40         Oklahoma
19718 5         2         42         Pennsylvania
19719 2         1         51         Virginia
19720 7         2         31         Nebraska
19721 2         1         36         New York
19722 2         2         18         Indiana
19723 2         1         6          California
19724 4         2         51         Virginia
19725 6         1         51         Virginia
19726 4         1         34         New Jersey
19727 5         1         37         North Carolina
19728 7         1         12         Florida
19729 1         1         25         Massachusetts
19730 3         1         25         Massachusetts
19731 4         1         4          Arizona
19732 7         1         51         Virginia
19733 4         2         47         Tennessee
19734 6         2         36         New York
19735 6         1         31         Nebraska
19736 4         1         31         Nebraska
19737 6         2         22         Louisiana
19738 4         2         16         Idaho
19739 4         1         6          California
19740 6         2         51         Virginia
19741 3         1         51         Virginia

In [26]:
genderdata <- post_180_nomissing [, c('vote_pres', 'income_group', 'gender')]
genderdata

      vote_pres income_group gender
1     1         1            2
2     2         5            1
3     2         3            2
4     1         3            2
5     2         4            1
6     2         5            2
7     2         4            1
8     2         3            1
9     2         5            2
10    2         4            2
11    1         3            2
12    2         3            1
13    1         4            2
14    1         1            2
15    2         3            2
16    2         3            2
17    1         3            2
18    2         4            1
19    1         1            1
20    2         5            1
21    1         2            2
22    1         4            2
23    2         3            2
24    2         4            1
25    2         3            1
26    2         3            2
27    1         1            2
28    1         5            2
29    2         3            1
30    2         4            2
⋮     ⋮         ⋮            ⋮
19712 2         3            2
19713 1         4            2
19714 1         1            1
19715 2         4            1
19716 1         3            2
19717 2         3            2
19718 2         5            1
19719 1         2            1
19720 2         1            2
19721 1         3            1
19722 2         2            2
19723 1         3            2
19724 2         4            1
19725 1         4            2
19726 1         3            2
19727 1         1            2
19728 1         1            2
19729 1         5            2
19730 1         4            1
19731 1         4            1
19732 1         2            2
19733 2         3            2
19734 2         4            2
19735 1         3            1
19736 1         4            1
19737 2         1            2
19738 2         4            2
19739 1         3            1
19740 2         3            2
19741 1         3            2

In [8]:
#table_sum_stats <- sumtable(post_180_nomissing, out='latex')
#^uncomment when we want the latex, this is really long
#table_sum_stats_df <- sumtable(post_180_nomissing, out='return')
#table_sum_stats_df

In [20]:
gendermodel <- lm(vote_pres ~ income_group + gender, data = genderdata)
summary(gendermodel)

Call:
lm(formula = vote_pres ~ income_group + gender, data = genderdata)

Residuals:
    Min      1Q  Median      3Q     Max
-0.5617 -0.4568 -0.3652  0.5298  0.6805

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept)   1.392085   0.015605  89.206   <2e-16 ***
income_group  0.045756   0.003145  14.548   <2e-16 ***
gender       -0.059177   0.007075  -8.365   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.4921 on 19738 degrees of freedom
Multiple R-squared:  0.01574,	Adjusted R-squared:  0.01564
F-statistic: 157.8 on 2 and 19738 DF,  p-value: < 2.2e-16

In [10]:
lm(vote_pres ~ income_group + education_4_cat, data = post_180_nomissing)

Call:
lm(formula = vote_pres ~ income_group + education_4_cat, data = post_180_nomissing)

Coefficients:
    (Intercept)     income_group  education_4_cat
        1.36195          0.05714         -0.03098

In [27]:
allmodel <- lm(vote_pres ~ income_group + education_4_cat + gender + race_ethnicity_seven + age_group, data = post_180_nomissing) 
summary(allmodel)

Warning message in model.response(mf, "numeric"):
“using type = "numeric" with a factor response will be ignored”
Warning message in Ops.factor(y, z$residuals):
“‘-’ not meaningful for factors”
Warning message in Ops.factor(r, 2):
“‘^’ not meaningful for factors”
ERROR while rich displaying an object: Error in quantile.default(resid): (unordered) factors are not allowed

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
6. repr::mime2repr[[mime]](obj)
7. repr_text.default(obj)
8. paste(capture.output(print(obj)), collapse = "\n")
9. capture.output(print(obj))
10. withVisible(...elt(i))
11. print(obj)
12. print.summary.lm(obj)
13. zapsmall(quantile(resid), digits + 1L)
14. quantile(resid)
15. quantile.default(resid)
16. stop("(unordered) factors are not allowed")