In [20]:
install.packages("languageserver")
install.packages('vtable')
install.packages('readr')
install.packages('dplyr')
install.packages('tidyverse')

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [1]:
library(readr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(vtable)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats 1.0.0     ✔ stringr 1.5.1
✔ ggplot2 3.5.1     ✔ tibble  3.2.1
✔ purrr   1.0.2     ✔ tidyr   1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: kableExtra


Attaching package: ‘kableExtra’


The following object is masked from ‘package:dplyr’:

    group_rows

In [2]:
elec_data <- read.csv('anes_timeseries_cdf_csv_20220916.csv')

In [3]:
subset <- elec_data[, c("VCF0004", "VCF0114", "VCF0104","VCF0705")]
subset <- na.omit(subset)
colnames(subset)[1]<-'year_of_study' #was VCF0004
colnames(subset)[2]<-'income_group' #was VCF0114
colnames(subset)[3]<-'gender' #was VCF0104
colnames(subset)[4]<-'vote_pres' #was VCF0705


subset

      year_of_study income_group gender vote_pres
1     1948          3            1      1
2     1948          5            2      2
3     1948          4            2      1
4     1948          5            2      2
5     1948          4            1      1
6     1948          5            2      2
7     1948          4            1      2
8     1948          1            2      1
9     1948          4            1      2
10    1948          4            1      1
11    1948          3            1      0
12    1948          3            1      2
13    1948          4            2      2
14    1948          5            2      1
15    1948          1            2      2
16    1948          5            1      2
17    1948          4            2      2
18    1948          3            2      1
19    1948          0            1      2
20    1948          2            1      1
21    1948          2            2      1
22    1948          2            1      1
23    1948          4            1      2
24    1948          5            1      1
25    1948          5            2      2
26    1948          4            2      2
27    1948          4            2      1
28    1948          5            2      2
29    1948          2            2      0
30    1948          2            2      2
⋮     ⋮             ⋮            ⋮      ⋮
68195 2020          1            1      0
68196 2020          3            1      0
68197 2020          4            1      2
68198 2020          2            2      0
68199 2020          1            1      0
68200 2020          4            2      1
68201 2020          3            2      1
68202 2020          1            2      1
68203 2020          1            2      1
68204 2020          5            2      1
68205 2020          4            1      1
68206 2020          1            1      1
68207 2020          4            1      1
68208 2020          1            2      0
68209 2020          2            2      1
68210 2020          2            2      0
68211 2020          1            2      0
68212 2020          3            2      2
68213 2020          4            2      2
68214 2020          3            1      1
68215 2020          1            1      2
68216 2020          1            2      0
68217 2020          4            1      1
68218 2020          1            2      2
68219 2020          0            2      2
68220 2020          2            2      0
68221 2020          4            2      2
68222 2020          3            1      1
68223 2020          3            2      2
68224 2020          3            2      1

In [4]:
subset$income_group <- as.factor(subset$income_group)
subset$gender <- as.factor(subset$gender)
subset$vote_pres <- as.factor(subset$vote_pres)
str(subset)

'data.frame':	47500 obs. of  4 variables:
 $ year_of_study: int  1948 1948 1948 1948 1948 1948 1948 1948 1948 1948 ...
 $ income_group : Factor w/ 6 levels "0","1","2","3",..: 4 6 5 6 5 6 5 2 5 5 ...
 $ gender       : Factor w/ 4 levels "0","1","2","3": 2 3 3 3 2 3 2 3 2 2 ...
 $ vote_pres    : Factor w/ 4 levels "0","1","2","3": 2 3 2 3 2 3 3 2 3 2 ...
 - attr(*, "na.action")= 'omit' Named int [1:20724] 2562 2563 2564 2565 2566 2567 2568 2569 2570 2571 ...
  ..- attr(*, "names")= chr [1:20724] "2562" "2563" "2564" "2565" ...

In [5]:
#filtering for after 1980, not including 1980
post_1980 <- filter(subset, year_of_study > 1980)


post_180_nomissing <- filter(post_1980, 
                       income_group != 0, 
                       gender != 0,
                       vote_pres != 0,
                        vote_pres != 3)

str(post_180_nomissing)

'data.frame':	20249 obs. of  4 variables:
 $ year_of_study: int  1984 1984 1984 1984 1984 1984 1984 1984 1984 1984 ...
 $ income_group : Factor w/ 6 levels "0","1","2","3",..: 2 6 4 4 6 5 6 5 4 6 ...
 $ gender       : Factor w/ 4 levels "0","1","2","3": 3 2 3 3 3 2 3 2 2 3 ...
 $ vote_pres    : Factor w/ 4 levels "0","1","2","3": 2 3 3 2 2 3 3 3 3 3 ...
 - attr(*, "na.action")= 'omit' Named int [1:20724] 2562 2563 2564 2565 2566 2567 2568 2569 2570 2571 ...
  ..- attr(*, "names")= chr [1:20724] "2562" "2563" "2564" "2565" ...

In [6]:
gendermodel <- lm(vote_pres ~ income_group + gender, data = post_180_nomissing)
summary(gendermodel)

Warning message in model.response(mf, "numeric"):
“using type = "numeric" with a factor response will be ignored”
Warning message in Ops.factor(y, z$residuals):
“‘-’ not meaningful for factors”
Warning message in Ops.factor(r, 2):
“‘^’ not meaningful for factors”
ERROR while rich displaying an object: Error in quantile.default(resid): (unordered) factors are not allowed

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
6. repr::mime2repr[[mime]](obj)
7. repr_text.default(obj)
8. paste(capture.output(print(obj)), collapse = "\n")
9. capture.output(print(obj))
10. withVisible(...elt(i))
11. print(obj)
12. print.summary.lm(obj)
13. zapsmall(quantile(resid), digits + 1L)
14. quantile(resid)
15. quantile.default(resid)
16. stop("(unordered) factors are not allowed")

In [36]:
table_sum_stats <- sumtable(post_180_nomissing, out='latex')

table_sum_stats_df <- sumtable(post_180_nomissing, out='return')
table_sum_stats_df

\begin{table}[!htbp] \centering \renewcommand*{\arraystretch}{1.1}\caption{Summary Statistics}\resizebox{\textwidth}{!}{
\begin{tabular}{lrrrrrrr}
\hline
\hline
Variable & N & Mean & Std. Dev. & Min & Pctl. 25 & Pctl. 75 & Max \\
\hline
year\_of\_study & 20249 & 2009 & 12 & 1984 & 2000 & 2020 & 2020 \\
income\_group & 20249 &  &  &  &  &  &  \\
... 0 & 0 & 0\% &  &  &  &  &  \\
... 1 & 2922 & 14\% &  &  &  &  &  \\
... 2 & 3078 & 15\% &  &  &  &  &  \\
... 3 & 7048 & 35\% &  &  &  &  &  \\
... 4 & 6003 & 30\% &  &  &  &  &  \\
... 5 & 1198 & 6\% &  &  &  &  &  \\
gender & 20249 &  &  &  &  &  &  \\
... 0 & 0 & 0\% &  &  &  &  &  \\
... 1 & 9263 & 46\% &  &  &  &  &  \\
... 2 & 10981 & 54\% &  &  &  &  &  \\
... 3 & 5 & 0\% &  &  &  &  &  \\
vote\_pres & 20249 &  &  &  &  &  &  \\
... 0 & 0 & 0\% &  &  &  &  &  \\
... 1 & 11375 & 56\% &  &  &  &  &  \\
... 2 & 8874 & 44\% &  &  &  &  &  \\
... 3 & 0 & 0\% &  &  &  &  & \\
\hline
\hline
\end{tabular}
}
\end{table}

   Variable      N     Mean Std. Dev. Min  Pctl. 25 Pctl. 75 Max
1  year_of_study 20249 2009 12        1984 2000     2020     2020
2  income_group  20249
3  ... 0         0     0%
4  ... 1         2922  14%
5  ... 2         3078  15%
6  ... 3         7048  35%
7  ... 4         6003  30%
8  ... 5         1198  6%
9  gender        20249
10 ... 0         0     0%
11 ... 1         9263  46%
12 ... 2         10981 54%
13 ... 3         5     0%
14 vote_pres     20249
15 ... 0         0     0%
16 ... 1         11375 56%
17 ... 2         8874  44%
18 ... 3         0     0%